name = "eventsourcing_sqlite"
version = "1.0.0"

description = "Sqlite event store for the Eventsourcing library"
licences = ["Apache-2.0"]
repository = { type = "github", user = "renatillas", repo = "eventsourcing_sqlite" }


[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
eventsourcing = ">= 2.0.0 and < 3.0.0"
sqlight = ">= 0.9.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
decode = ">= 0.2.0 and < 1.0.0"
gleam_json = ">= 1.0.1 and < 2.0.0"
birdie = ">= 1.1.8 and < 2.0.0"
pprint = ">= 1.0.3 and < 2.0.0"
